[versions]
# Kotlin
kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"

# Logging
log4j = "2.26.1"
slf4j = "2.0.18"

# Plugins
shadow = "9.6.1"

# Other dependencies
cloud-api = "0.1.0-platform.52-dev.1.1-7a06605"
caffeine = "3.2.4"
configurate = "4.2.0"

# Minestom
minestom = "2026.08.07-26.2"

[libraries]
# Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }

# Logging
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# Configurate
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

# Other dependencies
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
cloud-api = { module = "app.simplecloud.api:api", version.ref = "cloud-api" }

# Minestom
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
minestom-testing = { module = "net.minestom:testing", version.ref = "minestom" }

[bundles]
logging = ["log4j-core", "log4j-api", "log4j-slf4j-impl", "slf4j-api"]
configurate = ["configurate-yaml", "configurate-extra-kotlin"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }